# nix.yaml
# pdf-png-thumb generator workflow
# convert pdfs to png and png-thumbnails

name: pdf-png-thumb

on:
  push:
    paths:
      - 'pdf/*.pdf'
    branches:
      - 'main'  

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        - name: checkout
          uses: actions/checkout@v3
          
        - name: convert pdfs to png images
          run: |
            echo 'hi, nix'
            uname
            
            # add utils
            sudo apt-get install -y poppler-utils rename
                        
            # pdf documents for testing
            git clone https://github.com/dofufa/paper
            ls
            
            cd paper
            cp -r pdf ../
            
            tree .
            
            cd ..
            rm -rf paper
            
            ls
            tree .
                                    
            ls pdf

            rm -rf png thumb
            mkdir -p png thumb

            for entry in "pdf"/*
            do
              infile=$(basename "$entry")
              outfile="png/"${infile%.*}
              thumbfile="thumb/thumb-"${infile%.*}
              
              echo "pdftoppm -png $entry $outfile"
              pdftoppm -png $entry $outfile
              
              echo "pdftoppm -png -x 300 -y 300 -W 300 -H 300 $entry $thumbfile"
              pdftoppm -png -x 300 -y 300 -W 300 -H 300 $entry $thumbfile
            done

            ls png
            ls thumb

            # based on the solution found here:
            # https://unix.stackexchange.com/a/306258
            rename 's/-1.png/.png/' {png/*,thumb/*}

            ls png
            ls thumb
            
            ls
            
        - name: create sitemaps
          run: |
            echo 'hi, sitemap'
            uname
                        
            rm -rf txt
            mkdir -p txt
            
            baseurl=https://paper.dofufa.com
            
            grey_urls () {
              for entry in "$1"/*
              do
                infile=$(basename "$entry")
                echo "$baseurl/$1/$infile" >> txt/$1.txt
              done            
            }
           
            grey_urls "pdf"
            grey_urls "png"
            grey_urls "thumb"

        - name: show a tree
          run: |
            pwd
            tree .
            
        - name: setup git config
          run: |
            pwd
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            
        - name: commit
          run: |
            pwd
            git add .
            
            newstuff=$( git status | grep "Changes to be committed" | sed 's/ //g' )
            echo $newstuff
            
            echo ${#newstuff}
            
            if (( ${#newstuff} > 0 )); then
              git commit -m "generated by png-pdf-thumb workflow"
              git push origin main              
            fi
