# nix.yaml
# pdf-png-thumb

name: pdf-png-thumb

on:
  push:
#    paths:
#      - 'pdf/*.pdf'
#    branches:
#      - 'main'  

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        - name: checkout
          uses: actions/checkout@v3    
          
        - name: convert pdfs to png images
          run: |
            echo 'hi, nix'
            uname
            
            # add utils
            sudo apt-get install -y poppler-utils rename
                  
            # verbose logging
            ls pdf
            tree .
            
            # create fresh `png` and `thumb` dirs
            rm -rf png thumb
            mkdir -p png thumb

            for entry in "pdf"/*
            do
              infile=$(basename "$entry")
              outfile="png/"${infile%.*}
              thumbfile="thumb/thumb-"${infile%.*}
              
              echo "pdftoppm -png $entry $outfile"
              pdftoppm -png $entry $outfile
              
              echo "pdftoppm -png -x 300 -y 300 -W 300 -H 300 $entry $thumbfile"
              pdftoppm -png -x 300 -y 300 -W 300 -H 300 $entry $thumbfile
            done

            ls png
            ls thumb
            tree .

            # based on the solution found here:
            # https://unix.stackexchange.com/a/306258

            # cd png
            rename 's/-1.png/.png/' {png/*,thumb/*}

            ls png
            ls thumb
            tree .
            
            ls
            
        - name: show a tree
          run: |
            tree .
            
        - name: setup git config
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            
        - name: commit
          run: |
            git add .
            git commit -m "generated by pdf-png-thumb workflow for ubu-22"
            git push origin main
            
